services:
  - type: web
    name: kalix-erp
    runtime: docker
    plan: free
    rootDir: .
    startCommand: |
      php artisan migrate --force && supervisord -c /etc/supervisor/conf.d/supervisord.conf
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: kalix-db
          property: connectionString

databases:
  - name: kalix-db
    plan: free
